pipeline {
    agent any

    tools {
        jdk 'jdk21'
    }

    environment {
        JAVA_HOME = "${tool 'jdk21'}"
        PATH = "${env.JAVA_HOME}/bin:${env.PATH}"
	PROJECT_ID = 'faniverse'
        CLUSTER_NAME = 'k8s'
        LOCATION = 'asia-northeast3-a'
        CREDENTIALS_ID = 'gke'
    }
    
    stages {
        stage('Clone repository') {
            steps {
                git branch: 'yerim', url: 'https://github.com/20211129/Faniverse-DevOps.git'
            }
        }

        stage('Build Backend') {
            steps {
                dir('backend-repo/FaniverseBE') {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build'
                }
            }
        }

        stage('Build Image') {
            steps {
                script {
                    app = docker.build("yr20211129/faniverse_backend:latest", "backend-repo/FaniverseBE")
                }
            }
        }

        stage('Push image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'yr20211129') {
                        app.push("${env.BUILD_NUMBER}")
                        app.push("latest")
                    }
                }
            }
        }

	stage('Configure GKE credentials') {
            steps {
                script {
                    // GKE 클러스터 인증 설정
                    sh """
                        gcloud container clusters get-credentials ${env.CLUSTER_NAME} --zone ${env.LOCATION} --project ${env.PROJECT_ID}
                    """
                }
            }
        }
	    
        stage('Deploy to Kubernetes') {
            steps{
		// 기존 Secret 삭제 후 적용
            	sh 'kubectl delete secret faniverse-secret || true'
                sh 'kubectl apply -f backend-repo/FaniverseBE/faniverse-secret.yml'
        	sh 'kubectl apply -f backend-repo/FaniverseBE/deploy.yml'
            }
        }
    }
}
