apiVersion: apps/v1
kind: Deployment
metadata:
  name: faniverse-backend-deployment
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: faniverse-backend
  template:
    metadata:
      labels:
        app: faniverse-backend
    spec:
      containers:
      - name: faniverse-backend-container
        image: skaguswjd0212/faniverse-devops-project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SPRING_DATASOURCE_PASSWORD
        - name: GCP_STORAGE_CREDENTIALS_JSON
          valueFrom:
            secretKeyRef:
              name: gcp-secrets
              key: GCP_STORAGE_CREDENTIALS_JSON
        - name: GCP_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: gcp-secrets
              key: GCP_PROJECT_ID
        - name: GCP_BUCKET
          valueFrom:
            secretKeyRef:
              name: gcp-secrets
              key: GCP_BUCKET
