apiVersion: v1
kind: Secret
metadata:
  name: gcp-secrets
type: Opaque
data:
  GCP_PROJECT_ID: aGFuZHktY3VydmUtNDI4MTA3LWs3
  GCP_BUCKET: ZmFuaXZlcnNlLWJ1Y2tldA==
  GCP_STORAGE_CREDENTIALS_JSON: Y2xhc3NwYXRoOmhhbmR5LWN1cnZlLTQyODEwNy1rNy1kMzFjZWRhOGJlZTAuanNvbg==
